### ISSUE TITLE
SSL certificate problem: self-signed certificate

### ISSUE THREAD

**Issue by ghost** [brotkrueml/typo3-jobrouter-connector#8]
Hi Chris,

connection to JobRouter with self-signed certificate via https not working.

I deactivated the verifiy option in my typo3 test scenario, but i still get the connection error.

Is there any workaround / configuration to use a connection via ssl with self signed-certificate?

**Comment by brotkrueml** [comment]
Thanks for the request. This is not primarily an issue of the TYPO3 JobRouter Connector but of the underlying JobRouter Client. I created an issue for that: https://github.com/brotkrueml/jobrouter-client/issues/3

When the feature in JobRouter Client is available in a new version, the Connector must be adjusted so that the options can be set. I think, this will be done when configuring the connection. In the meantime you can adjust the following code in the **JobRouter Client** (look into the `vendor/brotkrueml/jobrouter-client` folder):

```diff
diff --git a/src/Client/RestClient.php b/src/Client/RestClient.php
index de0541f..60b9fad 100644
--- a/src/Client/RestClient.php
+++ b/src/Client/RestClient.php
@@ -57,7 +57,7 @@ final class RestClient implements ClientInterface
         $this->configuration = $configuration;
         $this->psr17factory = new Psr17Factory();
 
-        $client = new Curl($this->psr17factory);
+        $client = new Curl($this->psr17factory, ['verify' => false]);
         $this->browser = new Browser($client, $this->psr17factory);
         $this->browser->addMiddleware(new UserAgentMiddleware($this->configuration->getUserAgentAddition()));
         $this->authorisationMiddleware = new AuthorisationMiddleware();
```

Can you give feedback if this works?

Best way to use it is with [composer-patches](https://packagist.org/packages/cweagans/composer-patches), so the patch is applied every time a `composer install` or `composer update` is done.

Edit: The verification of the certificate is not done in this case, this can be a security incident. Best way would be to add the self-signed certificate to the available certificates as outlined here:
https://stackoverflow.com/questions/17597457/why-wont-curl-recognise-a-self-signed-ssl-certificate/21262787#21262787

**Comment by brotkrueml** [comment]
> I deactivated the verifiy option in my typo3 test scenario, but i still get the connection error.

Yes, TYPO3 uses Guzzle, the JobRouter Client (standalone library, which is then used by the TYPO3 JobRouter Connector) uses a lightweight alternative, named [Buzz](https://github.com/kriswallsmith/Buzz).

If I agree to this feature (don't know yet as it has security implications) the verfication should be turned-off only for one connection, not for all configured JobRouter connections, so using the configuration from TYPO3 is not an option.

What is the use case, why are you using a self-signed certificate (just curious)? An intranet installation where the certificate is installed in the user's browsers? Or a test/development installation?
